import os
import json
import asyncio
import base64
import httpx
import websockets
from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import Response

app = FastAPI()

SARVAM_API_KEY = os.environ.get("SARVAM_API_KEY", "sk_tcrxdvzl_c3m4CuhdXiuE3vL1rhKnCKY8")
SARVAM_WS_URL = "wss://api.sarvam.ai/v1/realtime"

ARIA_SYSTEM_PROMPT = """You are Aria, an Outbound SDR for Briskinfosec. Goal: qualify cybersecurity needs and book a 20-min discovery meeting. Tone: professional, consultative peer - never pushy. Flow: 1)Open-ask for 2 min 2)Context-industry/compliance 3)Probe-VAPT frequency,ISO27001/SOC2/RBI compliance,existing vendors 4)Position-CREST+CERT-In credentials,VAPT/RedTeam/Cloud/Compliance 5)Close-offer 20-min virtual call. Objections: has vendor->pivot to independent testing; not interested->one intel question; wants details->qualify focus first; in-house->explain compliance requires independent testing. Never guess technical answers-defer to senior consultant as reason to book meeting."""


@app.get("/")
async def health():
      return {"status": "Sarvam-Exotel Bridge running", "agent": "Aria SDR - Briskinfosec"}


@app.post("/exotel-webhook")
async def exotel_webhook(request: Request):
      form = await request.form()
      call_sid = form.get("CallSid", "unknown")
      from_number = form.get("From", "unknown")
      direction = form.get("Direction", "inbound")

    host = request.headers.get("host", "localhost")
    ws_url = f"wss://{host}/sarvam-ws/{call_sid}"

    exoxml = f"""<?xml version="1.0" encoding="UTF-8"?>
    <Response>
      <Connect>
          <Stream url="{ws_url}">
      <Parameter name="caller" value="{from_number}" />
      <Parameter name="direction" value="{direction}" />
    </Stream>
  </Connect>
</Response>"""
    return Response(content=exoxml, media_type="application/xml")


    @app.websocket("/sarvam-ws/{call_sid}")
    async def sarvam_websocket(websocket: WebSocket, call_sid: str):
        await websocket.accept()
            print(f"[{call_sid}] Exotel connected")

                sarvam_headers = {
                        "Authorization": f"Bearer {SARVAM_API_KEY}",
                                "Content-Type": "application/json"
    }

        sarvam_config = {
                "type": "session.update",
                        "session": {
                                    "instructions": ARIA_SYSTEM_PROMPT,
                                                "voice": "priya",
                                                            "input_audio_format": "pcm16",
                                                                        "output_audio_format": "pcm16",
                                                                                    "turn_detection": {
                                                                                                    "type": "server_vad",
                                                                                                                    "threshold": 0.5,
                                                                                                                                    "prefix_padding_ms": 300,
                                                                                                                                                    "silence_duration_ms": 700
                                                                                                                                                                }
                                                                                                                                                                        }
                                                                                                                                                                            }
                                                                                                                                                                            
                                                                                                                                                                                try:
                                                                                                                                                                                        async with websockets.connect(
                                                                                                                                                                                                    SARVAM_WS_URL,
                                                                                                                                                                                                                extra_headers=sarvam_headers
                                                                                                                                                                                                                        ) as sarvam_ws:
                                                                                                                                                                                                                                    print(f"[{call_sid}] Connected to Sarvam AI")
                                                                                                                                                                                                                                                await sarvam_ws.send(json.dumps(sarvam_config))
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            async def exotel_to_sarvam():
                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                async for message in websocket.iter_text():
                                                                                                                                                                                                                                                                                                                        data = json.loads(message)
                                                                                                                                                                                                                                                                                                                                                event = data.get("event", "")
                                                                                                                                                                                                                                                                                                                                                                        if event == "media":
                                                                                                                                                                                                                                                                                                                                                                                                    audio_payload = data["media"]["payload"]
                                                                                                                                                                                                                                                                                                                                                                                                                                audio_event = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "type": "input_audio_buffer.append",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "audio": audio_payload
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await sarvam_ws.send(json.dumps(audio_event))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif event == "stop":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"[{call_sid}] Call ended by Exotel")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except WebSocketDisconnect:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"[{call_sid}] Exotel disconnected")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def sarvam_to_exotel():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async for message in sarvam_ws:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data = json.loads(message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            msg_type = data.get("type", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if msg_type == "response.audio.delta":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                audio_delta = data.get("delta", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            media_msg = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "event": "media",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "media": {"payload": audio_delta}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await websocket.send_text(json.dumps(media_msg))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif msg_type == "response.audio.done":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mark_msg = {"event": "mark", "mark": {"name": "audio_done"}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await websocket.send_text(json.dumps(mark_msg))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"[{call_sid}] Sarvam error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await asyncio.gather(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exotel_to_sarvam(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sarvam_to_exotel()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"[{call_sid}] Bridge error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"[{call_sid}] Session ended")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await websocket.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pass
